server:
  port: 4100

spring:
  application:
    name: authenticationConsumer
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka


short:
  message:
    host: "https://gyytz.market.alicloudapi.com"
    path: "/sms/smsSend"
    method: "POST"
    appCode: "b134849cf9a948539f9015cb7cb1a4b9"
    smsSignId: "2e65b1bb3d054466b82f0c9d125465e2"
    templateId: "908e94ccf08b4476ba6c876d13f084ad"

ribbon:
  ReadTimeOut: 10000
  ConnectTimeOut: 10000
