server:
  port: 80
spring:
  application:
    name: zuulGateway
  redis:
    host: localhost
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    crowd-portal:
      service-id: authenticationConsumer
      path: /**
    crowd-project:
      service-id: projectConsumer
      path: /project/**
    crowd-order:
      service-id: orderConsumer
      path: /order/**
    crowd-pay:
      service-id: payConsumer
      path: /pay/**


#      分析：
#      1. 分析后得知/zuul的默认context-path是/zuul。
#      2. 之所以在默认的情况下我们不加zuul也可以请求成功是因为它帮我们做了url的裁剪。
#      （通俗的讲就是不加zuul.prefix=/zuul配置的话，以下两个url都可以请求成功
#      * http://localhost:16000/consumer/consumers/1
#      * http://localhost:16000/zuul/consumer/consumers/1）
#
#      解决：
#      1. 将默认context-path设置为空：zuul.servlet-path=/
#      2. 配置网关zuul的统一前缀:zuul.prefix=/zuul
#      (如果没有生效的话重启zuul服务)

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
