server:
  port: 7000
spring:
  application:
    name: payConsumer

  session:
    store-type: redis
  redis:
    host: localhost
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka


ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhNED5tQ2y+Zu3XpHZSPyJBPd/7r+Csgv3e8t2Zi/+zfiIquIKCWVYfbEpIBc5WhuBVv1aG0tQ6tcYdlPql0ZRs01hV/WrM2Imt/cl1cBl2L2xlZ0ajuUic1oD+zHo7eNW0hrUjHNTr+6rhid93Gxgu4hhQsCMDzsN13NxD/Ody1rEM8P+T9Lf97HXwScEh1y60EUqC1XVkP9q2XBNWg6nTgvX9NeXrwFeZR0qgmX/cdurN3A6fsOe+Og/qpdfAh0q0rivWXIQSZTLAOeVSppX19VMw3ft3bZhUE0+6blqCeBQSsjj12Km44v4tLKuYCotwYtZkRtBXKhEeXFVmJIGwIDAQAB
    app-id: 2021000117630093
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCWfr/JqGnnWbl81U1qcBtX7XzlFJaX/pAcfO3hi+C0uonFnO45ZBbCN3iy2AYmGn3E4M0/sQPIe3zGIJIoKBZP4VaStsb+0TlrjsZte/rzuXISg6GEwa+c7NZlSqT+RNMy5mWVYR1uMkbvCfqF+5jSAUZoSuWUBcCjBymm+ErkDlBhWCdFAtVxGlhV/XUXRLeEHMOF3EDuweodmBMhSkp6xOprixK3vDpz9iyQ51dd32R6Wp87b/y1CP1HTw6Zj/MHqt4BeABHcovvCyW4WyrRAW/SXr9vaI4Hn6J6dlb6v5V0NFjFSok6SIJSxIWSYJbYmBYnRuOCTOPt3P9KpPoxAgMBAAECggEAb7lHDiEuBedRUcBUiZkSY5NWLga7ybjdKZkBTHj4Z5M4JnFbVVXdo29k9nhzECSIi/lLxmXWZiZuufOCLbec4M5r4903HAMdOqEy5CKvafKZIe+AoDrd8YTNoULp/C4CEH6EmYIQRDek+16QEpl2mSkDKPe5OcuPeDggDumzR1u/accFCy6CcIr5K7neWWeeINSDvZu8/xkIlmBtnG+1N2LWZYUC6nVTKok2IgrKCGZmNE/5cl1paOshFztWNGDxolQkKbcZ+M6vsBSM/ZK2pEFiFn+qF+700hMtNPUI1mFZkuacCTqjK7RxwzmR0z2s7Qd7fRHTDjSFWnrNwJtyAQKBgQD/dpxA1uPfZcyafmCJ65Z57xZsz7zbhVCTVu9CLaBx887tHaz7U+QBjFubYLRadfS6V+XuZcqh56B1/4W47quy9BTltS2abgqtJQG9RjVxv8ZZGVGHrEzrR6xSGvtc/lX+bJ4M7Imy1QAW10/XdBPTLuKKBOqdnNFQqv9eYNb/kQKBgQCWz6+xnJRM13vYtzCZjd12Q7474uh8kIAkVa8tgGB2RMyiHGJGWUMQao/AL1Yu8bY2VzrxveJ0kUN/BdgMqYiFqWekkuLafgLLcA3lWUQechVwalDq6/Balwj6+VqQsN5Wg5RNamEU/4ckii/bLlXFhED92oJznvImsLGF+epAoQKBgB2CA9Zxe+zIA3Qs+NW1grIe7cYv0K7CnWYHeqd4Qbon4VT+QobdT87l+YbfCrYQPe5wTLzWwSsmaCB5HWcZGngXPXqzDMtzvoP1bFgCjhXPgwezpvk268OZicwKFdLOBfzXawIvKFChzdrVkAFhBRE1rzEmFDuUa5EXz1uFcBAhAoGAMZJW6ATV4mQ6O0QL3414LDWcREcTsE43MLpReJ1oF7gJo4e87e7NUooUclGc/JVLFZWatHd8BmDxVMFxAMiBLZ4/iSMXGkatWH2es7Kh53gMgAUSUAX53W0j8IsiL8lTbBCYINJE0wgjPemGTX9vhhsw2cCHfMXURs9xqt45F8ECgYB/NbfFAcvl4mOMtEBYVL8uBuIh350vtoNYRsnUoeMN+a4QEjlOMYAPhvXq/126BZaQa7VSU5HJwgRRToq3hv5n4x4rdIMdWXP4xkL8J+nr8LX29AGU3iXcCRWMm6Jqspn7CgHgnuc2ggPp5v8lDec+7UrsS0ldMV48QfiRUV83bQ==
    return-url: http://192.168.3.54/pay/return
    notify-url: http://pq3sv4.natappfree.cc/pay/notify
    sign-type: RSA2